syntax = "proto3";

package idp;

option go_package = "revenko.idp.v1;idpv1";

service AuthService {
  rpc GetPublicKey(GetPublicKeyRequest) returns (GetPublicKeyResponse);
  rpc Register(RegisterRequest) returns (RegisterResponse);
  rpc Login(LoginRequest) returns (LoginResponse);
  rpc Logout(LogoutRequest) returns (LogoutResponse);
  rpc RefreshToken(RefreshTokenRequest) returns (RefreshTokenResponse);
}

service ClientService {
  rpc ClientCreate(ClientCreateRequest) returns (ClientCreateResponse);
  rpc ClientDelete(ClientDeleteRequest) returns (ClientDeleteResponse);
}

message GetPublicKeyRequest {}

message GetPublicKeyResponse {
  bytes rsa_pub_pem = 1;
}

message ClientCreateRequest {
  string name = 1;
}

message ClientCreateResponse {
  string client_id = 1;
  string client_secret_token = 2;
}

message ClientDeleteRequest {
  string client_id = 1;
}

message ClientDeleteResponse {
  bool success = 1;
}

message RegisterRequest {
  string username = 1;
  string password = 2;
}

message RegisterResponse {
  string user_id = 1;
}

message LoginRequest {
  string username = 1;
  string password = 2;
  string client_id = 3;
}

message LoginResponse {
  string access_token = 1;
  string refresh_token = 2;
}

message LogoutRequest {
  string refresh_token = 1;
}

message LogoutResponse {
  bool success = 1;
}

message RefreshTokenRequest {
  string refresh_token = 1;
}

message RefreshTokenResponse {
  string access_token = 1;
  string refresh_token = 2;
}
